version: "3.9"
services:
  game:
    image: ubuntu:20.04
    working_dir: /home/chess
    ports:
      - "5555"
    depends_on:
      - database
    command: python server.py
  chat:
    image: ubuntu:20.04
    working_dir: /home/chess
    build: .
    ports:
      - "12321"
    depends_on:
      - game
      - database
    command: python chat_server.py
  database:
    build: .
    ports:
      - "27017"